"""Reporter Agent - Generates consolidated PR review report."""
import logging
from datetime import datetime

from arcus.agents.base import agent_handler, mark_section_failed, mark_section_ok
from arcus.contracts import PipelineEnvelope

logger = logging.getLogger(__name__)


def _generate_markdown_report(envelope: PipelineEnvelope) -> str:
    """
    Generate a comprehensive Markdown report from the envelope.

    Args:
        envelope: PipelineEnvelope with all analysis results.

    Returns:
        Markdown-formatted report.
    """
    lines: list[str] = []

    # Header
    lines.append("# Code Review Report")
    lines.append("")
    lines.append(f"**Repository**: {envelope.pr.repo_full_name}")
    lines.append(f"**PR #**: {envelope.pr.pr_number}")
    lines.append(f"**Commit**: `{envelope.pr.commit_sha}`")
    lines.append(f"**Report Generated**: {datetime.now().isoformat()}")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")

    # Count findings by severity
    consistency_findings = envelope.consistency.findings or []
    bug_findings = envelope.bugs.findings or []
    all_findings = consistency_findings + bug_findings

    high_count = sum(1 for f in all_findings if f.severity == "high")
    medium_count = sum(1 for f in all_findings if f.severity == "medium")
    low_count = sum(1 for f in all_findings if f.severity == "low")

    lines.append(f"**Total Issues Found**: {len(all_findings)}")
    lines.append(f"- 🔴 **High Severity**: {high_count}")
    lines.append(f"- 🟡 **Medium Severity**: {medium_count}")
    lines.append(f"- 🟢 **Low Severity**: {low_count}")
    lines.append("")

    # Pipeline Status
    lines.append("## Analysis Status")
    lines.append("")
    lines.append(f"- Context: `{envelope.context.status}`")
    lines.append(f"- Consistency: `{envelope.consistency.status}`")
    lines.append(f"- Bugs: `{envelope.bugs.status}`")
    lines.append(f"- Fixes: `{envelope.fixes.status}`")
    lines.append("")

    # Consistency Findings
    if consistency_findings:
        lines.append("## Consistency Issues")
        lines.append("")
        for finding in consistency_findings:
            _add_finding_to_report(lines, finding)
        lines.append("")

    # Bug Findings
    if bug_findings:
        lines.append("## Bugs & Security Issues")
        lines.append("")
        for finding in bug_findings:
            _add_finding_to_report(lines, finding)
        lines.append("")

    # Suggested Fixes
    if envelope.fixes.findings:
        lines.append("## Suggested Fixes")
        lines.append("")
        fixes_with_suggestions = [f for f in envelope.fixes.findings if f.fix]
        if fixes_with_suggestions:
            for finding in fixes_with_suggestions:
                _add_fix_to_report(lines, finding)
        else:
            lines.append("No automated fixes generated.")
        lines.append("")

    # Code Conventions (from context)
    if envelope.context.conventions:
        lines.append("## Detected Code Conventions")
        lines.append("")
        lines.append(f"- **Naming Convention**: {envelope.context.conventions.naming}")
        lines.append(
            f"- **Error Handling**: {envelope.context.conventions.error_handling}"
        )
        if envelope.context.conventions.notes:
            lines.append("- **Notes**:")
            for note in envelope.context.conventions.notes:
                lines.append(f"  - {note}")
        lines.append("")

    # Recommendations
    lines.append("## Recommendations")
    lines.append("")
    if high_count > 0:
        lines.append(
            "⚠️ **Address all HIGH severity issues before merging**. "
            "These may cause runtime failures or security vulnerabilities."
        )
        lines.append("")
    if medium_count > 0:
        lines.append(
            "→ **Review MEDIUM severity issues** carefully. "
            "Consider applying suggested fixes or addressing root causes."
        )
        lines.append("")
    if low_count > 0:
        lines.append(
            "💡 **LOW severity findings** are suggestions for improvement. "
            "Consider them for future refactoring."
        )
        lines.append("")

    if not all_findings:
        lines.append("✅ **No issues found!** Code looks good.")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Report generated by Arcus PR Review Pipeline*")
    lines.append(f"*Pipeline Run ID: {envelope.pipeline_run_id}*")

    return "\n".join(lines)


def _add_finding_to_report(lines: list[str], finding) -> None:  # type: ignore
    """Add a finding to the report."""
    severity_icon = {
        "high": "🔴",
        "medium": "🟡",
        "low": "🟢",
    }.get(finding.severity, "•")

    lines.append(f"### {severity_icon} {finding.title}")
    lines.append("")
    lines.append(f"**File**: `{finding.file}:{finding.line_start}-{finding.line_end}`")
    lines.append(f"**Type**: {finding.type}")
    lines.append(f"**Severity**: {finding.severity}")
    lines.append("")
    lines.append(f"{finding.rationale}")
    lines.append("")

    if finding.evidence_refs:
        lines.append("**References**:")
        for ref in finding.evidence_refs:
            lines.append(f"- {ref}")
        lines.append("")


def _add_fix_to_report(lines: list[str], finding) -> None:  # type: ignore
    """Add a fix suggestion to the report."""
    if not finding.fix:
        return

    lines.append(f"### Fix for: {finding.title}")
    lines.append("")
    lines.append(f"**File**: `{finding.file}`")
    lines.append(f"**Confidence**: {finding.fix.confidence}")
    lines.append("")
    lines.append(f"**Description**: {finding.fix.description}")
    lines.append("")

    if finding.fix.suggested_diff:
        lines.append("**Suggested Change**:")
        lines.append("")
        lines.append("```python")
        lines.append(finding.fix.suggested_diff)
        lines.append("```")
        lines.append("")


@agent_handler
def handle_reporter(envelope: PipelineEnvelope) -> PipelineEnvelope:
    """
    Generate consolidated PR review report.

    Handler for Reporter Agent (B8).
    - Reads all analysis results from envelope
    - Generates comprehensive Markdown report
    - Populates envelope.report with summary

    Args:
        envelope: PipelineEnvelope with complete analysis results.

    Returns:
        Updated envelope with report summary.
    """
    try:
        logger.info(
            f"Reporter generating report for {envelope.pr.repo_full_name}#{envelope.pr.pr_number}"
        )

        # Step 1: Generate report
        report_md = _generate_markdown_report(envelope)
        logger.debug(f"Generated report: {len(report_md)} characters")

        # Step 2: Create summary (first 200 chars of report)
        summary = report_md.split("\n")[0:5]  # First few lines
        summary_text = "\n".join(summary)

        # Step 3: Update envelope
        envelope.report.status = "ok"
        envelope.report.summary = summary_text
        envelope.report.comment_url = None  # In production, this would be set to the GitHub comment URL

        # Store full report in metadata if needed
        # In production, this could be stored in S3 and referenced
        logger.info("Report generated successfully")

        mark_section_ok(envelope, "report")

        return envelope

    except Exception as e:
        logger.error(f"Reporter failed: {type(e).__name__}: {e}", exc_info=True)
        mark_section_failed(
            envelope,
            "report",
            error_code="report_generation_failed",
            error_message=f"Failed to generate report: {str(e)}",
        )
        return envelope
